### ISSUE TITLE
Extensions - Split-Payment - not saving target % value without new line

### ISSUE THREAD

**Issue by arbadacarbaYK** [lnbits/splitpayments#1]
Neither an invoice-key nor a wallet-id will be saved as target if not an additional empty row is generated (inactive save button otherwise)

<img width="765" alt="220160818-3613b527-dc18-4b22-8961-2d60d1f0908a" src="https://user-images.githubusercontent.com/63317640/221196398-67b9a665-c2de-4971-b45c-db0acb65ea8a.png">
<img width="793" alt="220160826-6d3e2360-f2b8-46e4-949b-bd248b19f643" src="https://user-images.githubusercontent.com/63317640/221196406-b3a8b0d6-fb3d-469b-9ba2-6d9b89594f82.png">

btw wouldnt a lnurlp work as well ?

**Comment by bitkarrot** [comment]
Having same issue with the new extension in vetted extensions manifest
https://raw.githubusercontent.com/lnbits/lnbits-extensions/main/extensions.json

@dni if you don't have time to fix it, assign to me

**Comment by dni** [comment]
already addressed here: https://github.com/lnbits/splitpayments/pull/4

**Comment by dni** [comment]
i think this one is solved with latest release :)?
