### ISSUE TITLE
Double Split

### ISSUE THREAD

**Issue by MichaelAntonFischer** [lnbits/splitpayments#14]
Hi,

it seems that in Lnbits Versions 0.11.2 and 0.11.3 the Split plugin sometimes runs twice for the same transaction leading to double bookings.

The double booking in this image is from verison 0.11.3, the single booking after downgrading to 0.11.1

<img width="509" alt="image" src="https://github.com/lnbits/splitpayments/assets/93607398/a9570b39-223c-4373-a8a1-c0e7e3bf061e">

**Comment by MichaelAntonFischer** [comment]
Upon further checking:
The 0.11.1 version later also doubled the split. Downgrading the plugin to version 1 seems to help, will test further.

**Comment by MichaelAntonFischer** [comment]
Ok, upon further testing this issue is really dangerous for all Lnbits as a service users. It doubles the transactions and actually takes funds from the underlying node, falsifying the wallet balance in LNBits.

**Comment by MichaelAntonFischer** [comment]
UPDATE: I cannot recreate the error currently on my devserver neither on legends, will post updates if I manage to recreate it.

**Comment by MichaelAntonFischer** [comment]
Managed to recreate it:
Downgrade to 0.11.1 with Split 0.1.2 installed. Reupgrade to 0.11.3, issue appears.

After uninstalling and reinstalling the plugin, error disappears, just like with plugin downgrade.

The beahviour where the wallet balance goes negative does not constantly happen.

To test, here is my faulty setup: https://lnbitsdev.opago-pay.com/wallet?usr=20c245c3431d46778df93eea94cd18cb&wal=33f7db34094043a98a9b9e1f3d605ab2

<img width="513" alt="image" src="https://github.com/lnbits/splitpayments/assets/93607398/41a09ef3-c610-4e10-9fea-831db792b1f2">

**Comment by motorina0** [comment]
Does the `lnbits` server start with SSL certificates by default (`"--ssl-keyfile=... --ssl-certfile=....` flags)?

**Comment by thespielplatz** [comment]
What helped me https://github.com/lnbits/scrub/issues/7#issuecomment-1945646044

**Comment by dni** [comment]
lnbits `0.12.2` will fix this
