### ISSUE TITLE
Extension page bugs

### ISSUE THREAD

**Issue by Semisol** [lnbits/splitpayments#3]
- Cannot save after clicking clear
  Probably due to no targets existing after clearing.
- After clicking save, all split numbers are zeroed out. The API also gets sent `tag: null` instead of an empty string which also causes errors.
- If a tagged payment is processed, it still tries splitting. It should either split or process the tagged payment.

Some other things:
- What's the `extra.amount` check for?
- Tagged payments are confusing: they check for a specific field key existing. `extra.tag` or `extra.target` may want to be used instead.

**Comment by arbadacarbaYK** [comment]
see #1

**Comment by talvasconcelos** [comment]
> @Semisol new release should solve you issues? can you verify?

Deleting the last target, from the delete icon to the right, disables the save button, so I'm not allowed to save the change. Delete all targets works as expected though.
